[project]
name = "guardianeye"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.41.0",
    "mediapipe>=0.10.21",
]
